#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Resume-safe downloader for the structure manifest generated by build_full_target_manifest.py."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import requests
except ImportError as exc:
    raise SystemExit("Install dependency with: pip install requests") from exc


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_manifest(
    path: Path,
    max_rank: int,
    sources: set[str],
    include_optional: bool,
) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    selected: list[dict[str, str]] = []
    seen_filenames: set[str] = set()
    for row in rows:
        url = (row.get("download_url") or "").strip()
        filename = (row.get("filename") or "").strip()
        source = (row.get("structure_source") or "").strip()
        try:
            rank = int(row.get("candidate_rank") or "1")
        except ValueError:
            rank = 1
        enabled = (row.get("enabled_default") or "YES").strip().upper()
        if enabled in {"NO", "FALSE", "0"} and not include_optional:
            continue
        if not url or not filename or rank > max_rank:
            continue
        if sources and source not in sources:
            continue
        if filename in seen_filenames:
            continue
        seen_filenames.add(filename)
        selected.append(row)
    return selected


def download_one(
    row: dict[str, str],
    outdir: Path,
    *,
    timeout: float,
    attempts: int,
    overwrite: bool,
) -> dict[str, Any]:
    filename = row["filename"]
    url = row["download_url"]
    destination = outdir / filename
    partial = destination.with_suffix(destination.suffix + ".part")

    if destination.exists() and destination.stat().st_size > 0 and not overwrite:
        return {
            **row,
            "status": "SKIPPED_EXISTS",
            "path": str(destination),
            "bytes": destination.stat().st_size,
            "sha256": sha256_file(destination),
            "completed_at": utc_now(),
        }

    delay = 1.0
    headers = {"User-Agent": "ZoonoAI-structure-downloader/1.0"}
    last_error = ""
    for attempt in range(1, attempts + 1):
        try:
            with requests.get(url, stream=True, timeout=timeout, headers=headers) as response:
                if response.status_code in (429, 500, 502, 503, 504):
                    raise RuntimeError(f"retryable HTTP {response.status_code}")
                response.raise_for_status()
                with partial.open("wb") as handle:
                    for chunk in response.iter_content(chunk_size=1024 * 1024):
                        if chunk:
                            handle.write(chunk)
            if partial.stat().st_size == 0:
                raise RuntimeError("downloaded file is empty")
            os.replace(partial, destination)
            return {
                **row,
                "status": "DOWNLOADED",
                "path": str(destination),
                "bytes": destination.stat().st_size,
                "sha256": sha256_file(destination),
                "completed_at": utc_now(),
            }
        except Exception as exc:
            last_error = f"{type(exc).__name__}: {exc}"
            try:
                partial.unlink(missing_ok=True)
            except Exception:
                pass
            if attempt < attempts:
                time.sleep(delay)
                delay = min(delay * 2, 20.0)

    return {
        **row,
        "status": "FAILED",
        "path": str(destination),
        "bytes": 0,
        "sha256": "",
        "error": last_error,
        "completed_at": utc_now(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--outdir", type=Path, required=True)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--timeout", type=float, default=90.0)
    parser.add_argument("--attempts", type=int, default=5)
    parser.add_argument("--max-rank", type=int, default=1, help="1 downloads representative only")
    parser.add_argument(
        "--sources",
        default="RCSB,AlphaFold",
        help="Comma-separated: RCSB,AlphaFold",
    )
    parser.add_argument("--include-optional", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    sources = {x.strip() for x in args.sources.split(",") if x.strip()}
    rows = read_manifest(
        args.manifest,
        max_rank=args.max_rank,
        sources=sources,
        include_optional=args.include_optional,
    )
    print(f"Selected {len(rows):,} unique files", flush=True)

    results: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
        futures = {
            executor.submit(
                download_one,
                row,
                args.outdir,
                timeout=args.timeout,
                attempts=args.attempts,
                overwrite=args.overwrite,
            ): row
            for row in rows
        }
        completed = 0
        for future in as_completed(futures):
            result = future.result()
            results.append(result)
            completed += 1
            print(
                f"[{completed}/{len(rows)}] {result['status']}: {result.get('filename','')}",
                flush=True,
            )

    log_jsonl = args.outdir / "download_audit.jsonl"
    with log_jsonl.open("w", encoding="utf-8") as handle:
        for result in results:
            handle.write(json.dumps(result, ensure_ascii=False) + "\n")

    summary = {
        "generated_at": utc_now(),
        "selected": len(rows),
        "downloaded": sum(r["status"] == "DOWNLOADED" for r in results),
        "skipped": sum(r["status"] == "SKIPPED_EXISTS" for r in results),
        "failed": sum(r["status"] == "FAILED" for r in results),
        "audit_log": str(log_jsonl),
    }
    (args.outdir / "download_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 1 if summary["failed"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
